from docx import Document
from docx.shared import Inches
import io
import datetime
from utils.logger import logger

def generate_docx_report(image_buffer, prediction_label, confidence_score, confidence_percent, gradcam_buffer=None):
    logger.info(f"Generating DOCX report for label : {prediction_label}")
    doc = Document()

    doc.add_heading("Thyrovision: Thyroid Cancer Detection Report", 0)
    doc.add_paragraph(f"Date : {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    doc.add_heading("Analysis Results, 1")

    p = doc.add_paragraph()
    p.add_run("Prediction: ").bold = True
    p.add_run(f"{prediction_label}\n")

    p.add_run("Confidence Score: ").bold = True
    p.add_run(f"{confidence_score:.4f}\n")

    p.add_run("Confidence Percentage: ").bold = True
    p.add_run(f"{confidence_percent:.2f}%")

    doc.add_heading("Original Image", level= 1)
    if image_buffer:
        image_buffer.seek(0)
        doc.add_picture(image_buffer, width=Inches(4.0))

    if gradcam_buffer:
        doc.add_heading("Grad-CAM Interpretability", 1)
        doc.add_paragraph("The heatmap below visualizes the regions of the image ")
        gradcam_buffer.seek(0)
        doc.add_picture(gradcam_buffer, width=Inches(4.0))


    doc.add_heading("Disclaimer:", 1)
    doc.add_paragraph(
        """
        This report is generated by an artificial intelligence system and intended for assistive decision-making
        only. It does not constitute a final medical diagnosis. All findings should be reviewed and verified by a
        qualified radiologist or medical professional.
        """
    )

    doc_buffer = io.BytesIO()
    doc.save(doc_buffer)
    doc_buffer.seek(0)

    return doc_buffer